name: "CI Run"
on:
  pull_request:
    branches:
      - main
      - grok/*/*
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: |
          bash tests/run.sh
